#############
### build ###
#############

# base image
FROM node:12.18.4 as build

#Maintainers
LABEL maintainer=" Anil Kumar Golla <anilkumar.golla@bostonlogix.com>"

# environment Variables

ENV port=8080
ENV app_environment=prod
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@10.1.3

# add app
COPY . /app

# generate build
RUN ng build --$app_environment --output-path=dist

############
### prod ###
############

# base image
FROM nginxinc/nginx-unprivileged:1.19.4

#Remove the default conf
RUN rm -rf /etc/nginx/conf.d/default.conf

#Copy the custom  conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE $port

# run nginx
CMD ["nginx", "-g", "daemon off;"]
