#############
### build ###
#############

# base image
FROM node:12.18.4 as build

#Maintainers
LABEL maintainer=" Anil Kumar Golla <anilkumar.golla@bostonlogix.com>"

# environment Variables

ENV port=80
ENV app_environment=prod
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@10.1.3

# add app
COPY . /app

# generate build
RUN ng build --$app_environment --output-path=dist

############
### prod ###
############

# base image
#FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
#COPY --from=build /app/dist /usr/share/nginx/html

# expose port
EXPOSE $port

# run nginx
#CMD ["ng serve --port $port"]
#CMD ["ng","serve","--port",$port,"--host", "0.0.0.0", "--disable-host-check"]
CMD ng serve --host 0.0.0.0 --port $port --disable-host-check
